Repository Leon-Art-EIP/Front, pull requests merged in 2024-11, with the labels that each got.

#75 Fix/conversations overflow/leon-563
  __test__/components/chat/chats/ChatList.test.tsx
  src/components/chat/chats/ChatList.tsx
  src/components/navbar/notifications/Notifications.tsx
Labels: bug, testing

#77 Fix/show password/leon-517
  src/app/register/page.tsx
  src/forms/tsx/LoginForm.tsx
  src/forms/tsx/RegisterForm.tsx
Labels: bug, enhancement

#78 [ADD] username modification button, error handling and connection to backend
  src/wrappers/settings/me/SettingsMeWrapper.tsx
Labels: enhancement

#87 [FIX] put the show password button inside the custom Input component … LEON-610
  src/app/reset_password/[token]/form.tsx
  src/components/form/Input.tsx
  src/forms/tsx/LoginForm.tsx
  src/forms/tsx/RegisterForm.tsx
  src/forms/tsx/SettingsPasswordForm.tsx
Labels: bug, enhancement

#88 [FIX] show dateTime on hover of message LEON-590
  src/components/chat/messages/Chat.tsx
  src/components/chat/messages/ChatBox.tsx
  src/components/chat/messages/MessageInput.tsx
Labels: bug, enhancement

#89 [FIX] UI of article's title in home page LEON-588
  src/components/home/passingArt/PassingArt.tsx
Labels: bug, enhancement

#92 [ADD] possibility to select multiple filters
  src/components/explorer/PriceFilters.tsx
  src/wrappers/explorer/ExplorerWrapper.tsx
Labels: enhancement

#97 Fix/reload when cancel order+canceled payment page/leon 633/leon 634
  src/app/single/[id]/canceled/page.tsx
  src/components/form/Input.tsx
  src/components/single-art-page/card/SingleArtPageCard.tsx
  src/contexts/OrderContext.tsx
Labels: bug, enhancement
